public class BoatSoldController {
    
    public PageReference Bayinshore() {
        return Page.Bayinshore;
    }
     
    public PageReference Centerinshore() {
        return Page.Centerinshore;
    }    
    
    public PageReference Flatinshore() {
        return Page.Flatinshore;
    }
     
    public PageReference Centeroffshore() {
        return Page.Centeroffshore;
    }
    
    public PageReference Convertibleoffshore() {
        return Page.Convertibleoffshore;
    }
    
    public PageReference Walkaroundoffshore() {
        return Page.Walkaroundoffshore;
    }
}