@isTest
public class BoatSoldControllerTest {
    
    @isTest static void testBayBoat(){
      
    //  Boat_Sold__c b = new Boat_Sold__c(Name= 'Boat1', Source__c='Web',  
    //   Works__c='Gen Repairs', S);
    //   insert b;
       
 //    Test.StartTest();
 
 //    PageReference pageRef = Page.;
 //       Test.setCurrentPage(pageRef);
        
 //       ApexPages.currentPage().getParameters().put('id', String.valueOf(b.Id));
      
 //    updateRecordCon controller = new updateRecordCon();
 //      controller.updateRecord();
 
 //      controller.init();    
 //   PageReference prf = controller.updateRecord();
 //    System.assertEquals(null, prf); //assertion
 //       Test.StopTest();
    }


}